# Generated by Django 4.0.8 on 2024-01-11 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('code_comp', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('libelle_comp', models.CharField(max_length=255)),
                ('desc_comp', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id_entreprise', models.BigAutoField(primary_key=True, serialize=False)),
                ('forme_juridique', models.CharField(max_length=255)),
                ('raison_sociale', models.CharField(max_length=255)),
                ('adresse_ent', models.TextField()),
                ('tel_ent', models.CharField(max_length=10)),
                ('c_postal', models.CharField(max_length=20)),
                ('ville', models.CharField(max_length=255)),
                ('fax', models.CharField(max_length=10)),
                ('contact_nom', models.CharField(max_length=255)),
                ('tel_contact', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id_Etud', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('n_et_promo', models.IntegerField()),
                ('qualite_etud', models.CharField(choices=[('Mme', 'Mme'), ('M', 'M')], max_length=5)),
                ('nom_etud', models.CharField(max_length=255)),
                ('prenom_etud', models.CharField(max_length=255)),
                ('adresse_etud', models.TextField()),
                ('suite', models.CharField(blank=True, max_length=255, null=True)),
                ('c_postal', models.CharField(max_length=20)),
                ('ville', models.CharField(max_length=255)),
                ('sexe', models.CharField(choices=[('M', 'Femme'), ('H', 'Homme')], max_length=1)),
                ('date_naissance', models.DateField()),
                ('tel_etud', models.CharField(max_length=20)),
                ('mention', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id_prof', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('qualite_prof', models.CharField(choices=[('Mme', 'Mme'), ('M', 'M')], max_length=5)),
                ('nom_prof', models.CharField(max_length=255)),
                ('prenom_prof', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse_prof', models.TextField(blank=True, null=True)),
                ('tel_prof_eco', models.CharField(blank=True, max_length=20, null=True)),
                ('c_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('ville', models.CharField(blank=True, max_length=255, null=True)),
                ('tel_prof_dom', models.CharField(blank=True, max_length=20, null=True)),
                ('date_depart', models.DateField(blank=True, null=True)),
                ('date_embauche', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('annee_promo', models.DateField(primary_key=True, serialize=False)),
                ('nb_inscr', models.IntegerField(blank=True, null=True)),
                ('nb_recus', models.IntegerField(blank=True, null=True)),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.prof')),
            ],
        ),
        migrations.CreateModel(
            name='TypeStage',
            fields=[
                ('id_type_stage', models.BigAutoField(primary_key=True, serialize=False)),
                ('nb_sem', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tuteur',
            fields=[
                ('id_tuteur', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('qualite_t', models.CharField(choices=[('Mme', 'Mme'), ('M', 'M')], max_length=5)),
                ('nom_t', models.CharField(max_length=255)),
                ('prenom_t', models.CharField(max_length=255)),
                ('tel_t', models.CharField(max_length=10)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('n_stage', models.BigAutoField(primary_key=True, serialize=False)),
                ('annee_stage', models.DateField()),
                ('compte_rendu', models.TextField(blank=True, null=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.entreprise')),
                ('id_type_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.typestage')),
                ('n_et_promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.etudiant')),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.prof')),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.promo')),
                ('tuteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tuteur')),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='promo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.promo'),
        ),
        migrations.CreateModel(
            name='Acquerir',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('niveau_exige', models.IntegerField()),
                ('code_comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.competence')),
                ('id_type_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.typestage')),
            ],
        ),
    ]
